name: PatBeta1
favicon: null
layout_spectrum: 0.74473
typography_spectrum: 0
title: Patros Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171f32'
    - '#236fbd'
    - '#a38d20'
    - '#b0bf8d'
    - '#dfb518'
  brandStrength: 0.3125
  lightness: 0.28934099012985826
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
